'use strict';

let options = {};
if (process.env.NODE_ENV === 'production') {
  options.schema = process.env.SCHEMA;  // define your schema in options object
}

module.exports = {
  up: async (queryInterface, Sequelize) => {
    options.tableName = 'Spots';
    return queryInterface.bulkInsert(options, [
      {
        ownerId: 1,
        address: '1345 Picketts Lane',
        city: 'Colorado Springs',
        state: 'Colorado',
        country: 'United States',
        lat: 11.5,
        lng: 40.2,
        name: 'Spring Forward',
        description: 'Enjoy Colorado Springs with a great view',
        price: 285,
      },
      {
        ownerId: 2,
        address: '5422',
        city: 'San Diego',
        state: 'California',
        country: 'United States',
        lat: 30.3,
        lng: 40.2,
        name: 'Sunny Days',
        description: 'Relax and enjoy California',
        price: 429,
      },
      {
        ownerId: 3,
        address: '9028',
        city: 'Jacksonville',
        state: 'Florida',
        country: 'United States',
        lat: 60.3,
        lng: 51.7,
        name: 'Hurricane Central',
        description: 'Dont let the name fool you. It is safe!',
        price: 84,
      },
      {
        ownerId: 1,
        address: '4568',
        city: 'Boise',
        state: 'Idaho',
        country: 'United States',
        lat: 43,
        lng: 115.6,
        name: 'Potato Land',
        description: 'Free potatoes for your taking!',
        price: 167,
      },
      {
        ownerId: 1,
        address: '7894',
        city: 'Lansing',
        state: 'Michigan',
        country: 'United States',
        lat: 42,
        lng: 84,
        name: 'The Great Water',
        description: 'Come drink some of our famous water!',
        price: 220,
      },
      {
        ownerId: 2,
        address: '1423',
        city: 'Annapolis',
        state: 'Maryland',
        country: 'United States',
        lat: 39,
        lng: 77,
        name: 'Downtown Dream',
        description: 'Enjoy downtown by the water with many attractions!',
        price: 550,
      },
      {
        ownerId: 1,
        address: '6589',
        city: 'Austin',
        state: 'Texas',
        country: 'United States',
        lat: 30,
        lng: 97,
        name: 'Texas Twang',
        description: 'House of the best BBQ sauce around. Featured at every Mission BBQ!',
        price: 90,
      },
      {
        ownerId: 1,
        address: '4568',
        city: 'Phoenix',
        state: 'Arizona',
        country: 'United States',
        lat: 33,
        lng: 112,
        name: 'Hot But Not Humid',
        description: 'Enjoy the rocks!',
        price: 310,
      },
      {
        ownerId: 2,
        address: '4125',
        city: 'Paris',
        state: 'France',
        country: 'United States',
        lat: 48,
        lng: 1,
        name: 'Home in the Eiffel',
        description: 'Stay in the Eiffel Tower and see Paris with a view!',
        price: 880,
      },
      {
        ownerId: 3,
        address: '9713',
        city: 'Olympia',
        state: 'Washington',
        country: 'United States',
        lat: 47,
        lng: 123,
        name: 'Little Bit of Everything',
        description: 'Enjoy your stay where you can see mountains, rivers, valleys, and have trip to the ocean',
        price: 450,
      },
      {
        ownerId: 1,
        address: '5641',
        city: 'Oakhurst',
        state: 'California',
        country: 'United States',
        lat: 37,
        lng: 119,
        name: 'Yosemite Views',
        description: 'About an hour drive outside of Yosemite National Park!',
        price: 220,
      },
      {
        ownerId: 2,
        address: '5432',
        city: 'Owington',
        state: 'Nevada',
        country: 'United States',
        lat: 37,
        lng: 119,
        name: 'Temple',
        description: 'The temple is a great place to relax with your friends.',
        price: 240,
      },
      {
        ownerId: 2,
        address: '1745',
        city: 'Wrightsville',
        state: 'Pennsylvania',
        country: 'United States',
        lat: 37,
        lng: 119,
        name: 'Cabin with a Hot Tub!',
        description: "Need a lakeside getaway? Look no further than this 3-bedroom, 2-bath vacation rental! Sitting across the street from Clarke Lake, this Wrightsville cabin is complete with an open living space, fully equipped kitchen, and a deck perfect for summer days spent outdoors. When you aren't out on the water, grab a delicious ice cream at the Turkey Hill Experience or stroll the stalls of the Lancaster Central Market.",
        price: 354,
      },
      {
        ownerId: 3,
        address: '5641',
        city: 'Rhinebeck',
        state: 'New York',
        country: 'United States',
        lat: 37,
        lng: 119,
        name: 'The Deep',
        description: "Unique experience, secluded. Enjoy a weekend or a few days eco-friendly retreat in an architectural, geometric masterpiece on 30 preserved acres just minutes from all that Rhinebeck and the Hudson Valley have to offer.",
        price: 472,
      },
      {
        ownerId: 3,
        address: '1234',
        city: 'Walhalla',
        state: 'South Carolina',
        country: 'United States',
        lat: 37,
        lng: 119,
        name: 'Treehouse Daydreams',
        description: 'Why do people travel thousands of miles from around the world to stay in our treehouse? Come and see for yourself!! Transport your spirit, and feel a thrill that can only be discovered in the treetops! Experience the one-of-a-kind blend of youthful bliss and grown-up luxury for yourself. The faster you get here, the sooner you change your pace and unwind in our wooden paradise.',
        price: 535,
      },
      {
        ownerId: 2,
        address: '9862',
        city: 'Pownal',
        state: 'Vermont',
        country: 'United States',
        lat: 37,
        lng: 119,
        name: 'The Smurf Layer',
        description: "Owl Hill House is an organically shaped structure built by a group of sculptors in the early 1980's and recently renovated by one of its original creators. Its 570 square feet interior is bright, airy and cozy with hand-plastered, sculptural, white walls and custom built-in furniture. It is set in a tranquil clearing surrounded by beautiful trees on a private Vermont dirt road, and is the perfect base for exploring northern Berkshire County's cultural gems and southern Vermont’s picturesque towns and natural beauty, or to just relax and leave the rectilinear world behind.",
        price: 199,
      },
      {
        ownerId: 1,
        address: '5641',
        city: 'Yert',
        state: 'Nevada',
        country: 'United States',
        lat: 37,
        lng: 119,
        name: 'Spaceship House',
        description: "Are you ready for a vacation that's out of this world?!  Come stay in our newly-remodeled spaceship-on-the-beach! Whether you're a Trekkie, a Star-Wars buff, or just the *coolest* grandparents on planet Earth--You're sure to find something delightful in this deep-space dome. ",
        price: 168,
      },
      {
        ownerId: 2,
        address: '4561',
        city: 'Tremosine sul Garda',
        state: 'Brescia',
        country: 'Italy',
        lat: 37,
        lng: 119,
        name: 'Early Risers',
        description: "This house in Italy is nestled at the base of the stunning mountains, offering breathtaking views of the surrounding natural beauty. With its rustic architecture and cozy interior, it's the perfect retreat for nature lovers looking to escape the hustle and bustle of city life. Whether you're looking to hike the nearby trails, enjoy local cuisine, or simply unwind in peaceful seclusion, this mountain-side abode is sure to exceed your expectations.",
        price: 146,
      },
    ], {});
  },

  down: async (queryInterface, Sequelize) => {
    options.tableName = 'Spots';
    const Op = Sequelize.Op;
    return queryInterface.bulkDelete(options, {
      name: { [Op.in]: ['Temple', 'Cabin with a Hot Tub!', 'The Deep', 'Treehouse Daydreams', 'The Smurf Layer', 'Spaceship House', 'Early Risers', 'Spring Forward', 'Sunny Days', 'Hurricane Central', 'Potato Land', 'The Great Water', 'Downtown Dream', 'Texas Twang', 'Hot But Not Humid', 'Home in the Eiffel', 'Little Bit of Everything', 'Yosemite Views'] }
    }, {});
  }
};
